config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'newsfeed'
    resources :friendings, only: [:index]
    resource :profile, except: [:new, :destroy]
    resources :photos do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Photo' }
      resources :comments, defaults: { commentable: 'Photo' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end

    resources :posts do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Post' }
      resources :comments, defaults: { commentable: 'Post' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end
  end

  resources :friendings, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  root 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_token

  has_one :profile, inverse_of: :user, dependent: :destroy
  has_many :posts, inverse_of: :user
  has_many :likes, inverse_of: :user
  has_many :comments, inverse_of: :user
  has_many :photos, inverse_of: :user, 
            dependent: :destroy
  
  has_many :initiated_friendings, 
            foreign_key: :friender_id,
            class_name: "Friending"

  has_many :friended_users,
           through: :initiated_friendings,
           source: :friend_recipient

  has_many :received_friendings,
           foreign_key: :friend_id,
           class_name: "Friending"

  has_many :users_friended_by,
           through: :received_friendings,
           source: :friend_initiator

  belongs_to :avatar, class_name: 'Photo'

  belongs_to :cover_photo, class_name: 'Photo'

  has_secure_password

  validates :email, presence: true

  validates :email, 
            length: { in: 8..48 },
            uniqueness: true

  validates :password,
            length: { in: 4..24 },
            allow_nil: true

  validate :avatar_belongs_to_user

  validate :cover_photo_belongs_to_user

  accepts_nested_attributes_for :profile,
                     reject_if: :all_blank

  def friends
    # TODO: Change to SQL
    friended_users + users_friended_by
  end

  def friends=(friend)
    friended_users << friend
  end

  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: self[:auth_token])
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end

  def newsfeed(last_n=10)
    # Collect user's friends.
    post_creators = []
    friends.each { |friend| post_creators << friend.id }
    # Collect posts from those friends, order created_at DESC.
    Post.where('user_id IN (?)', post_creators).order('created_at DESC').limit(last_n)
  end

  def self.search(query)
    if query
      where('email LIKE ?', "%#{query}%")
    else
      where("")
    end
  end

  private

  def self.send_welcome_email(id)
    user = User.find(id)
    UserMailer.delay.welcome(user)
    # TODO: Add link to timeline in mailer
  end

  def avatar_belongs_to_user
    avatar.user_id == id if avatar
  end

  def cover_photo_belongs_to_user
    cover_photo.user_id == id if cover_photo
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :require_current_user, only: [:update, :destroy, :newsfeed]

  def index
    @users = User.search(params[:query])
  end

  def new
    if current_user
      redirect_to user_posts_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(whitelisted_user_params)
    if @user.save
      User.delay.send_welcome_email(@user.id)
      sign_in(@user)
      flash[:success] = "Created new user!"
      redirect_to user_posts_path(@user)
    else
      flash.now[:error] = "Failed to create user!"
      render :new
    end
  end

  def show
  end

  def update
    # TODO: Fix photos show view with set avatar links
    @user = User.find(params[:id])
    if @user.update(whitelisted_user_params)
      flash[:success] = "Updated user!"
      redirect_to user_posts_path(@user)
    else
      flash[:error] = "Failed to update user!"
      redirect_to request.referrer
    end
  end

  def destroy
    if current_user.destroy
      sign_out
      flash[:success] = 'User destroyed'
      redirect_to root_path
    else
      flash[:error] = 'User failed to destroy'
      redirect_to root_path
    end
  end

  def newsfeed
    @user = User.find(params[:user_id])
    @newsfeed = @user.newsfeed.order('id DESC')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def whitelisted_user_params
    params.require(:user).permit(:email, 
                         :password,
                         :password_confirmation,
                         :avatar_id,
                         :cover_photo_id,
                         { profile_attributes: [
                          :quote,
                          :about_me,
                          :first_name, 
                          :last_name, 
                          :day, 
                          :month, 
                          :year, 
                          :gender] }
                         )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Posts', user_posts_path(user) %></td>
        <td><%= link_to 'About', user_profile_path(user) %></td>
        <% if user == current_user %>
          <td><%= link_to 'Edit', edit_user_profile_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render partial: 'user_form' %>

app/views/users/newsfeed.html.erb
<p><%= link_to 'User Profile', user_profile_path(@user) %></p>
<p><%= link_to 'User Posts', user_posts_path(@user) %></p>

<% if current_user == @user %>
  <%= form_for [current_user, current_user.posts.build] do |post_fields| %>

    <%= post_fields.label :body %>
    <%= post_fields.text_area :body %>

    <%= post_fields.submit %>
  <% end %>
<% end %>

<% @newsfeed.each do |newsfeed_post| %>
  <div style='border: 2px solid black'>
    <h4><%= newsfeed_post.user.profile.full_name %></h4>
    <div class='media'>
      <%= render partial: 'user_avatar', locals: { user: newsfeed_post.user } %>
    </div>

    <div class='media-body'>
      <%= newsfeed_post.body %><br>
      <% if newsfeed_post.likes.find_by_user_id(current_user.id).nil? %>
        <%= link_to "Like(#{newsfeed_post.likes.count})", user_post_likes_path(current_user, newsfeed_post), method: :post %>
      <% else %>
        <%= link_to "Unlike(#{newsfeed_post.likes.count})", user_post_like_path(current_user, newsfeed_post, Like.where(user_id: current_user.id, likeable_id: newsfeed_post.id, likeable_type: 'Post').first.id), method: :delete %>
      <% end %>

      <% if current_user %>
        <%= form_for [current_user, newsfeed_post, newsfeed_post.comments.build] do |comment_fields| %>
          <%= comment_fields.label :body %>
          <%= comment_fields.text_area :body %>
          <%= comment_fields.hidden_field :commentable_id, value: newsfeed_post.id %>
          <%= comment_fields.hidden_field :commentable_type, value: 'Post' %>
          <%= comment_fields.submit %>
        <% end %>
      <% end %>

      <% newsfeed_post.comments.order('id DESC').each do |comment| %>
        <% if comment.author %>
          <p><strong><%= comment.author.profile.full_name %>: </strong><%= comment.body %></p>
        <% end %>
        
        <% if comment.likes.find_by_user_id(current_user.id).nil? && comment.author_id %>
          <%= link_to "Like(#{comment.likes.count})", user_post_comment_likes_path(current_user, newsfeed_post, comment), method: :post %>
        <% elsif comment.author_id %>
          <%= link_to "Unlike(#{comment.likes.count})", user_post_comment_like_path(current_user, newsfeed_post, comment, comment.likes.find_by_user_id(current_user.id)), method: :delete %>
        <% end %>
        
        <% if comment.author_id == current_user.id %>
          <%= link_to 'Delete', user_post_comment_path(current_user, newsfeed_post, comment), method: :delete %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>