config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'newsfeed'
    resources :friendings, only: [:index]
    resource :profile, except: [:new, :destroy]
    resources :photos do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Photo' }
      resources :comments, defaults: { commentable: 'Photo' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end

    resources :posts do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Post' }
      resources :comments, defaults: { commentable: 'Post' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end
  end

  resources :friendings, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  root 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  has_many :comments, as: :commentable,
                      dependent: :destroy
                      
  has_many :likes, as: :likeable,
                   dependent: :destroy

  has_attached_file :image, styles: { 
                    medium: "200x200", 
                    thumb: "50x50" }, 
                    s3_host_name: "s3-us-west-2.amazonaws.com"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.to_s
    'Photo'
  end

  def photo_from_url(url)
    self.photo = open(url)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user
  before_action :require_current_user, only: [:create, :destroy]
  before_action :require_user_friend, only: [:show]

  def index
    @photos = @user.photos.order('created_at DESC')
    @photo = Photo.new
  end

  def create
    @photo = @user.photos.build(whitelisted_photo_params)
    if @photo.save
      flash[:success] = 'Photo uploaded'
      redirect_to user_photos_path(@user)
    else
      flash[:error] = 'Photo failed to upload'
      redirect_to user_photos_path(@user)
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:success] = 'Photo destroyed'
    else
      flash[:error] = 'Photo failed to destroy'
    end
    redirect_to user_photos_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def require_user_friend
    unless current_user.friends.include?(@user) || (current_user == @user)
      flash[:error] = 'Not authorized'
      redirect_to request.referrer
    end
  end

  def whitelisted_photo_params
    params.require(:photo).permit(:image)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/index.html.erb
<%= render partial: 'photo_form' if current_user == @user %>
<br>
<% unless @photos.nil? %>
  <% @photos.each do |photo| %>
    <%= link_to user_photo_path(@user, photo) do %>
      <%= image_tag photo.image.url(:thumb) %>
    <% end %>
  <% end %>
<% end %>

app/views/photos/new.html.erb
<%= render partial: 'photo_form' %>

app/views/photos/show.html.erb
<div class='row'>
  <div class='col-sm-5 col-sm-offset-1'>
    <h1><%= @photo.image_file_name %></h1>
    <%= image_tag @photo.image.url(:medium) %>

    <% if @photo.likes.find_by_user_id(current_user.id).nil? %>
      <p><%= link_to "Like(#{@photo.likes.count})", user_photo_likes_path(current_user, @photo), method: :post %></p>
    <% else %>
      <p><%= link_to "Unlike(#{@photo.likes.count})", user_photo_like_path(current_user, @photo, Like.where(user_id: current_user.id, likeable_id: @photo.id, likeable_type: 'Photo').first.id), method: :delete %></p>
    <% end %>
    
    <% if @user.id == current_user.id %>
      <p><%= link_to 'Set as Avatar', user_path(current_user, user: { avatar_id: @photo.id }), method: :put %></p>
      <p><%= link_to 'Set as Cover Photo', user_path(current_user, user: { cover_photo_id: @photo.id }), method: :put %></p>
      <p><%= link_to 'Delete Photo', user_photo_path(current_user, @photo), method: :delete %></p>
    <% end %>
  </div>
  
  
  <div class='col-sm-5' data-photo-id="<%= @photo.id %>">

    <% if current_user %>
      <%= form_for [current_user, @photo, @photo.comments.build], remote: true do |comment_fields| %>
        <%= comment_fields.label :body, class: 'sr-only' %>
        <%= comment_fields.text_area :body, class: 'new-comment' %>
        <%= comment_fields.hidden_field :commentable_id, value: @photo.id %>
        <%= comment_fields.hidden_field :commentable_type, value: 'Photo' %>
        <%= comment_fields.submit 'Comment' %>
      <% end %>
    <% end %>
    
    <div class='container-fluid comment-list' id='comments-<%= @photo.id %>'>
      <% @photo.comments.order('created_at DESC').each do |comment| %>
        <%= render partial: 'comment', locals: { user: @user, parent: @photo, comment: comment } %>
      <% end %>
    </div>
  </div>
</div>