config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'newsfeed'
    resources :friendings, only: [:index]
    resource :profile, except: [:new, :destroy]
    resources :photos do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Photo' }
      resources :comments, defaults: { commentable: 'Photo' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end

    resources :posts do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Post' }
      resources :comments, defaults: { commentable: 'Post' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end
  end

  resources :friendings, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  root 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable,
                      dependent: :destroy
                      
  has_many :likes, as: :likeable,
                   dependent: :destroy

  accepts_nested_attributes_for :comments

  validates :body, :user, presence: true

  validates :body, length: { in: 1..1000 }

  def self.to_s
    'Post'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: [:index, :create, :show, :edit, :update, :destroy]
  before_action :require_current_profile_user, except: [:show, :index]

  def index
    @posts = @user.posts.order('id DESC')
    @post = Post.new
  end

  def create
    @post = @user.posts.build(whitelisted_post_params)
    respond_to do |format|
      if @post.save
        format.js {}
        format.html { redirect_to request.referrer }
      else
        format.js {}
        format.html { redirect_to request.referrer }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.destroy
        format.js {}
      else
        format.js {}
      end
    end
  end
  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def whitelisted_post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.js.erb
var $posts = $('#posts');
var currentPost = '<%= j(render partial: "post", locals: { user: @user, post: @post }) %>';
$posts.prepend(currentPost);
$('#new-post').val('');

app/views/posts/destroy.js.erb
var currentPost = $("[data-post-id=<%= j(@post.id.to_s) %>]");
currentPost.remove();

app/views/posts/index.html.erb
<section class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <%= render partial: 'user_cover_photo', locals: { user: @user } %>
  </div>
</section>

<section class="row">
  <nav class="col-sm-10 col-sm-offset-1 tab-bar navbar navbar-default">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <%= render partial: 'user_avatar', locals: { user: @user } %>
        <p class="name"><%= @user.profile.full_name %></p>

        <ul class="nav navbar-nav page-links">
          <li class="active">
            <%= link_to 'Timeline', user_posts_path(@user), class: 'btn btn-link' %>
          </li>
          <li>
            <%= link_to 'About', user_profile_path(@user), class: 'btn btn-link' %>
          </li>
          <li>
            <%= link_to 'Photos', user_photos_path(@user), class: 'btn btn-link' %>
          </li>
          <li>
            <%= link_to 'Friends', user_friendings_path(@user), class: 'btn btn-link' %>
          </li>
          <% if current_user == @user %>
            <li>
              <%= link_to 'Newsfeed', user_newsfeed_path(@user), class: 'btn btn-link' %>
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>
</section>

<section class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <aside class="col-sm-4">

      <!--About block -->
      <section class="row">
        <header class="timeline-subpage-header">
          <div class="container-fluid">
            <p>About</p>
          </div>
        </header>

        <div class="timeline-subpage">
          <p>Born on: July 31st, 1980</p>
          <p>Went to school at: Hogwarts</p>
          <p>Hometown: Godrick's Hollow, England</p>
          <p>Currently Lives: Godrick's Hollow</p>
        </div>
      </section>

      <!-- Photos block -->
      <section class="row">
        <header class="timeline-subpage-header">
          <div class="container-fluid">
            <p>Photos (<%= @user.photos.count %>)</p>
          </div>
        </header>

        <div class="timeline-subpage">
          <div class="timeline-photos">
            <% @user.photos[0..8].each do |photo| %>
              <%= image_tag photo.image.url(:thumb) %>
            <% end %>
          </div>

          <!-- <a href="#">See More Photos</a> -->
        </div>
      </section>

      <!-- Friends block -->
      <section class="row">
        <header class="timeline-subpage-header">
          <div class="container-fluid">
            <p>Friends (<%= @user.friends.count %>)</p>
          </div>
        </header>

        <div class="timeline-subpage">
          <div class="col-sm-4 timeline-friends">
            <% @user.friends[0..5].each do |friend| %>
              <div class='col-sm-4'>
              <%= render partial: 'user_avatar', locals: { user: friend } %>
              <%= link_to "#{friend.profile.full_name}", user_posts_path(friend), class: 'col-sm-4' %>
              </div>
            <% end %>

          <!-- <a href="#">See More Friends</a> -->
        </div>
      </section>
    </aside>

    <article class="col-sm-8">

      <!--New post block -->
      <section class="row">
        <header class="timeline-subpage-header">
          <div class="container-fluid">
            <p>Post</p>
          </div>
        </header>

        <div class="timeline-subpage post-box">
          <div class="container-fluid">
            <% if current_user == @user %>
              <%= form_for [@user, @post], remote: true do |post_fields| %>
                <%= render partial: 'post_errors' %>

                <%= post_fields.label :body, class: 'sr-only' %>
                <%= post_fields.text_area :body, id: 'new-post' %>
          </div>
        </div>

        <footer class="subpage-footer">
          <div class="container-fluid">
            
                <%= post_fields.submit 'Post', class: 'btn btn-primary pull-right post-button' %>
              <% end %>
            <% end %>
          
          </div>
        </footer>
      </section>

      <!-- Post block -->
      <section class="row" id="posts">
        <% @posts.each do |post| %>
          <%= render partial: 'post', locals: { user: @user, post: post } %>
        <% end %>

      </section>
    </article>
  </div>
</section>

<% unless current_user == @user %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfriend #{@user.profile.first_name}", friending_path(@user), method: :delete, remote: true %>
  <% else %>
    <%= link_to "Friend #{@user.profile.first_name}", friendings_path(id: @user.id), method: :post, remote: true %> 
  <% end %>
<% end %>