config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'newsfeed'
    resources :friendings, only: [:index]
    resource :profile, except: [:new, :destroy]
    resources :photos do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Photo' }
      resources :comments, defaults: { commentable: 'Photo' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end

    resources :posts do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Post' }
      resources :comments, defaults: { commentable: 'Post' } do
        resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      end
    end
  end

  resources :friendings, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  root 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def sign_in(user)
    user.regenerate_auth_token
    cookies[:auth_token] = user.auth_token
    @current_user = user
    @current_user == user && cookies[:auth_token] == user.auth_token
  end

  def permanent_sign_in(user)
    user.regenerate_auth_token
    cookies.permanent[:auth_token] = user.auth_token
    @current_user = user
    @current_user == user && cookies[:auth_token] == user.auth_token
  end

  def sign_out
    @current_user = nil
    cookies.permanent[:auth_token] = cookies[:auth_token] = nil
    @current_user.nil? && cookies[:auth_token].nil?
  end

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def signed_in_user?
    !!current_user
  end
  helper_method :signed_in_user?

  def require_login
    unless signed_in_user?
      flash[:error] = 'Unauthorized, please sign in'
      redirect_to login_path
    end
  end

  def require_current_user
    unless (params[:id] == current_user.id.to_s) || (params[:user_id] == current_user.id.to_s)
      flash[:error] = "You're not authorized to view this"
      redirect_to request.referrer || root_path
    end
  end

  def require_current_profile_user
    unless params[:user_id] == current_user.id.to_s
      flash[:error] = "You're not authorized to view this"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_links
    if signed_in_user?
      str = "#{render partial: 'logged_in_header'}"
    else
      str = "#{render partial: 'logged_out_header'}"
    end
    str.html_safe
  end
end

app/views/application/_comment.html.erb
<div class='row comment' data-comment-id='<%= comment.id %>'>
  <% if comment.author %>
    <p><%= comment.author.profile.full_name %>: <%= comment.body %></p>
  <% end %>

  <% if comment.likes.find_by_user_id(current_user.id).nil? && comment.author_id %>
    <%= link_to "Like(#{comment.likes.count})", polymorphic_url([current_user, parent, comment, @like]), method: :post, class: 'comment-liking' %>
  <% elsif comment.author_id %>
    <%= link_to "Unlike(#{comment.likes.count})", polymorphic_url([current_user, parent, comment, comment.likes.find_by_user_id(current_user.id)]), method: :delete, class: 'comment-liking' %>
  <% end %>

  <% if comment.author_id == current_user.id %>
    <%= link_to 'Delete', polymorphic_url([current_user, parent, comment]), method: :delete, remote: true %>
  <% end %>
</div>

app/views/application/_logged_in_header.html.erb
<nav class="topnav navbar navbar-default col-sm-12">
  <div class="container-fluid">

    <!--Danebook logo -->
    <div class="logo-container">
      <%= image_tag("danish_flag.gif", alt: 'Danebook Logo', class: "navbar-brand pull-left") %>
      <a class="navbar-brand pull-left" href="<%= user_posts_path(current_user) %>" >Danebook</a>
    </div>

    <!-- Search bar and name -->
    <%= form_tag users_path, class: 'navbar-form navbar-right form-inline', role: 'search', method: 'get' do %>
      <div class='form-group'>
        <%= label_tag :query, "Find User By Email" %>
        <%= text_field_tag :query, "", class: 'form-control', placeholder: 'foo@bar.com' %>
        <%= submit_tag "Search" %>
      </div>
      <%= link_to "Logout", logout_path, :method => :delete %>
    <% end %>
  </div>

</nav>

app/views/application/_logged_out_header.html.erb
<nav class="topnav navbar navbar-default col-xs-12">
  <!-- Jumbotron logo -->
  <div class="logo-container">
    <a class="navbar-brand pull-left" href="#">Danebook</a>
  </div>

  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <!--  end of extra mobile stuff -->

  <!--Email/password inputs -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <%= form_tag session_path do %>

      <%= label_tag do %>
        Email
        <%= text_field_tag :email %>
      <% end %>

      <%= label_tag do %>
        Password
        <%= password_field_tag :password %>
      <% end %>

      <%= label_tag do %>
        Remember me?
        <%= check_box_tag :remember_me %>
      <% end %>

      <%= submit_tag "Log in" %>
    <% end %>
  </div>

</nav>

app/views/application/_photo_errors.html.erb
<% if @photo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

    <ul>
    <% @photo.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_photo_form.html.erb
<%= form_for [@user, @photo] do |photo_fields| %>
  <%= render partial: 'photo_errors' %>

  <%= photo_fields.label :image %>
  <%= photo_fields.file_field :image %>

  <%= photo_fields.submit %>
<% end %>

app/views/application/_post.html.erb
<div class='user-post' data-post-id="<%= post.id %>" >  
  <div class="timeline-subpage">
    <div class="container-fluid">
      <div class="col-sm-2">
        <%= render partial: 'user_avatar', locals: { user: @user } %>
      </div>

      <div class="col-sm-10">
        <p><%= post.user.profile.full_name %><br>Posted on <%= post.created_at %></p>
      </div>

      <div class="col-sm-12 post-text">
        <p><%= post.body %></p>
      </div>
    </div>
  </div>

  <footer class="subpage-footer">
    <div class="container-fluid">
      <% if post.likes.find_by_user_id(current_user.id).nil? %>
        <%= link_to "Like(#{post.likes.count})", user_post_likes_path(current_user, post), method: :post, class: 'post-liking' %>
      <% else %>
        <%= link_to "Unlike(#{post.likes.count})", user_post_like_path(current_user, post, Like.where(user_id: current_user.id, likeable_id: post.id, likeable_type: 'Post').first.id), method: :delete, class: 'post-liking' %>
      <% end %>

      <% if current_user == @user %>
        <%= link_to 'Delete', user_post_path(@user, post), class: 'pull-right', method: :delete, remote: true %>
      <% end %>

      <% if current_user %>
        <%= form_for [current_user, post, post.comments.build], remote: true do |comment_fields| %>
          <%= comment_fields.label :body, class: 'sr-only' %>
          <%= comment_fields.text_area :body, class: 'new-comment' %>
          <%= comment_fields.hidden_field :commentable_id, value: post.id %>
          <%= comment_fields.hidden_field :commentable_type, value: 'Post' %>
          <%= comment_fields.submit 'Comment', class: 'btn btn-primary pull-right' %>
        <% end %>
      <% end %>

      <div class='container-fluid comment-list' id="comments-<%= post.id %>">
        <% post.comments.order('created_at DESC').each do |comment| %>
          <%= render partial: 'comment', locals: { user: @user, parent: post, comment: comment } %>
        <% end %>
      </div>
    </div>
  </footer>
</div>

app/views/application/_post_errors.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_profile_errors.html.erb
<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

    <ul>
    <% @profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_user_avatar.html.erb
<% if user.avatar %>
  <%= image_tag user.avatar.image.url(:thumb) %>
<% else %>
  <%= image_tag('user_silhouette_generic.gif', size: '50') %>
<% end %>

app/views/application/_user_cover_photo.html.erb
<% if user.cover_photo %>
  <%= image_tag user.cover_photo.image.url(:medium) %>
<% else %>
  <%= image_tag('hogwarts_small.jpg') %>
<% end %>

app/views/application/_user_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_user_form.html.erb
<section class="row container-fluid">
  <main class="col-sm-6 col-sm-offset-1">

    <header>Connect with all your friends!</header>

    <ul>
      <li>See photos and updates in your news feed.</li>
      <li>Post your status for the world to see from your profile.</li>
      <li>Get in touch with your friends by "friending" them.</li>
      <li>Like things because you're a positive person!</li>
    </ul>

  </main><!--

  --><div class="col-sm-4">

    <h1>Sign Up</h1>

    <%= form_for @user do |user_fields| %>
      <%= render partial: 'user_errors' %>

      <%= user_fields.label :email %>
      <%= user_fields.text_field :email %>
      <br>
      <%= user_fields.label :password %>
      <%= user_fields.password_field :password %>
      <br>
      <%= user_fields.label :password_confirmation %>
      <%= user_fields.password_field :password_confirmation %>
      <br>
      <%= user_fields.fields_for :profile, Profile.new do |profile_fields| %>
        <%= profile_fields.label :first_name %>
        <%= profile_fields.text_field :first_name %>
        <br>
        <%= profile_fields.label :last_name %>
        <%= profile_fields.text_field :last_name %>
        <br>
        <%= profile_fields.label :day %>
        <%= profile_fields.select :day, 1..31 %>

        <%= profile_fields.label :month %>
        <%= profile_fields.select :month, 1..12 %>

        <%= profile_fields.label :year %>
        <%= profile_fields.select :year, 1900..2000 %>
        <br>
        <%= profile_fields.label :gender %>
        Male
        <%= profile_fields.radio_button('gender', 'Male') %>
        Female
        <%= profile_fields.radio_button('gender', 'Female') %>
        <br>
      <% end %>
      <br>
      <%= user_fields.submit %>
    <% end %>

  </div>

</section>